import type { RoleDefinition } from "@/domain/entities";

export const AUTHORIZATION_VERSION = 1;

export const INITIAL_ROLES: readonly RoleDefinition[] = [
  {
    key: "administrator",
    name: "Administradora",
    version: AUTHORIZATION_VERSION,
    permissionKeys: ["*"],
  },
  {
    key: "lawyer",
    name: "Abogado",
    version: AUTHORIZATION_VERSION,
    permissionKeys: [
      "dashboard.view",
      "consultations.view",
      "consultations.create",
      "consultations.edit",
      "clients.view",
      "clients.create",
      "clients.edit",
      "cases.view",
      "cases.create",
      "cases.edit",
      "cases.finalize",
      "documents.view",
      "tasks.view",
      "tasks.create",
      "tasks.edit",
      "events.view",
      "events.create",
      "events.edit",
    ],
  },
  {
    key: "assistant",
    name: "Asistente",
    version: AUTHORIZATION_VERSION,
    permissionKeys: [
      "dashboard.view",
      "consultations.view",
      "consultations.create",
      "consultations.edit",
      "clients.view",
      "clients.create",
      "clients.edit",
      "cases.view",
      "cases.edit",
      "documents.view",
      "tasks.view",
      "tasks.create",
      "tasks.edit",
      "events.view",
      "events.create",
      "events.edit",
    ],
  },
  {
    key: "reception",
    name: "Recepción",
    version: AUTHORIZATION_VERSION,
    permissionKeys: [
      "dashboard.view",
      "consultations.view",
      "consultations.create",
      "consultations.edit",
      "clients.view",
      "clients.create",
      "tasks.view",
      "tasks.create",
      "events.view",
      "events.create",
    ],
  },
] as const;
